languageCode = "en"
languageName = "English"
weight = 2
title = "Kody Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"

[author]
name = "Kody Black"
image = "img/kapibal.jpg"
headline = "Actions speak louder than words."
bio = "A little bit about you"
links = [ { link = "https://github.com/kody-black/blog" }, { github = "https://github.com/kody-black" }, { x-twitter = "https://x.com/DistinyKody" } ]
